// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIke9DY9xmnQ93ropVKYE5d20QKGaftcU',
    appId: '1:888462818841:web:db8ab07960948267ebb488',
    messagingSenderId: '888462818841',
    projectId: 'td-issue-tracker',
    authDomain: 'td-issue-tracker.firebaseapp.com',
    storageBucket: 'td-issue-tracker.firebasestorage.app',
    measurementId: 'G-9VZTE644TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC64XQaP4IY50YUohffIhf3aNAHwCgDOoM',
    appId: '1:888462818841:android:af401cb8a35d8511ebb488',
    messagingSenderId: '888462818841',
    projectId: 'td-issue-tracker',
    storageBucket: 'td-issue-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDuQWxuIjit_VQOZZp_B_je5qH7PV59M',
    appId: '1:888462818841:ios:84beef52e76936b6ebb488',
    messagingSenderId: '888462818841',
    projectId: 'td-issue-tracker',
    storageBucket: 'td-issue-tracker.firebasestorage.app',
    iosBundleId: 'com.example.internalIssueTrackingPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDuQWxuIjit_VQOZZp_B_je5qH7PV59M',
    appId: '1:446593438820:ios:41e9bffdc1886a020bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    iosBundleId: 'com.example.internalIssueTrackingPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3199keJUPn8UuPnIg6PyBQtmgQV4ul7U',
    appId: '1:446593438820:web:c5ca3c9ba35efeb00bbb71',
    messagingSenderId: '446593438820',
    projectId: 'tracking-portal-eab05',
    authDomain: 'tracking-portal-eab05.firebaseapp.com',
    storageBucket: 'tracking-portal-eab05.firebasestorage.app',
    measurementId: 'G-1R7CP7FYL9',
  );
}
